2025-05-09 16:58:17,345 INFO    MainThread:3441732 [internal.py:wandb_internal():93] W&B internal server running at pid: 3441732, started at: 2025-05-09 16:58:17.344768
2025-05-09 16:58:17,348 DEBUG   HandlerThread:3441732 [handler.py:handle_request():140] handle_request: run_start
2025-05-09 16:58:17,349 INFO    WriterThread:3441732 [datastore.py:open_for_write():75] open: /home/user/pyo/Rec-with-TKG/wandb/offline-run-20250509_165816-97lfifi0/run-97lfifi0.wandb
2025-05-09 16:58:17,363 DEBUG   HandlerThread:3441732 [meta.py:__init__():35] meta init
2025-05-09 16:58:17,363 DEBUG   HandlerThread:3441732 [meta.py:__init__():49] meta init done
2025-05-09 16:58:17,363 DEBUG   HandlerThread:3441732 [meta.py:probe():209] probe
2025-05-09 16:58:17,370 DEBUG   HandlerThread:3441732 [meta.py:_setup_git():199] setup git
2025-05-09 16:58:17,392 DEBUG   HandlerThread:3441732 [meta.py:_setup_git():206] setup git done
2025-05-09 16:58:17,392 DEBUG   HandlerThread:3441732 [meta.py:_save_pip():53] save pip
2025-05-09 16:58:17,393 DEBUG   HandlerThread:3441732 [meta.py:_save_pip():67] save pip done
2025-05-09 16:58:17,393 DEBUG   HandlerThread:3441732 [meta.py:_save_conda():74] save conda
2025-05-09 16:58:18,778 DEBUG   HandlerThread:3441732 [meta.py:_save_conda():84] save conda done
2025-05-09 16:58:18,779 DEBUG   HandlerThread:3441732 [meta.py:probe():247] probe done
2025-05-09 19:19:26,782 WARNING MainThread:3441732 [internal.py:wandb_internal():153] Internal process interrupt: 1
2025-05-09 19:19:30,912 WARNING MainThread:3441732 [internal.py:wandb_internal():153] Internal process interrupt: 2
2025-05-09 19:19:30,912 ERROR   MainThread:3441732 [internal.py:wandb_internal():156] Internal process interrupted.
2025-05-09 19:19:30,918 INFO    SenderThread:3441732 [sender.py:finish():1114] shutting down sender
2025-05-09 19:19:31,768 INFO    WriterThread:3441732 [datastore.py:close():279] close: /home/user/pyo/Rec-with-TKG/wandb/offline-run-20250509_165816-97lfifi0/run-97lfifi0.wandb
2025-05-09 19:19:31,786 INFO    HandlerThread:3441732 [handler.py:finish():806] shutting down handler
2025-05-09 19:19:31,789 INFO    MainThread:3441732 [internal.py:handle_exit():80] Internal process exited
